//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18408
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IHM_Reservation.WebServiceConsultation {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hotel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int starsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string countryField;
        
        private double priceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int stars {
            get {
                return this.starsField;
            }
            set {
                if ((this.starsField.Equals(value) != true)) {
                    this.starsField = value;
                    this.RaisePropertyChanged("stars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                if ((object.ReferenceEquals(this.countryField, value) != true)) {
                    this.countryField = value;
                    this.RaisePropertyChanged("country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vol", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Vol : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string fromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string toField;
        
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string categoryField;
        
        private System.DateTime dateStartField;
        
        private System.DateTime dateEndField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string from {
            get {
                return this.fromField;
            }
            set {
                if ((object.ReferenceEquals(this.fromField, value) != true)) {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string to {
            get {
                return this.toField;
            }
            set {
                if ((object.ReferenceEquals(this.toField, value) != true)) {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string category {
            get {
                return this.categoryField;
            }
            set {
                if ((object.ReferenceEquals(this.categoryField, value) != true)) {
                    this.categoryField = value;
                    this.RaisePropertyChanged("category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime dateStart {
            get {
                return this.dateStartField;
            }
            set {
                if ((this.dateStartField.Equals(value) != true)) {
                    this.dateStartField = value;
                    this.RaisePropertyChanged("dateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime dateEnd {
            get {
                return this.dateEndField;
            }
            set {
                if ((this.dateEndField.Equals(value) != true)) {
                    this.dateEndField = value;
                    this.RaisePropertyChanged("dateEnd");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceConsultation.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément city de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListHotels", ReplyAction="*")]
        IHM_Reservation.WebServiceConsultation.GetListHotelsResponse GetListHotels(IHM_Reservation.WebServiceConsultation.GetListHotelsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListHotels", ReplyAction="*")]
        System.Threading.Tasks.Task<IHM_Reservation.WebServiceConsultation.GetListHotelsResponse> GetListHotelsAsync(IHM_Reservation.WebServiceConsultation.GetListHotelsRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément from de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListVols", ReplyAction="*")]
        IHM_Reservation.WebServiceConsultation.GetListVolsResponse GetListVols(IHM_Reservation.WebServiceConsultation.GetListVolsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetListVols", ReplyAction="*")]
        System.Threading.Tasks.Task<IHM_Reservation.WebServiceConsultation.GetListVolsResponse> GetListVolsAsync(IHM_Reservation.WebServiceConsultation.GetListVolsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListHotelsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListHotels", Namespace="http://tempuri.org/", Order=0)]
        public IHM_Reservation.WebServiceConsultation.GetListHotelsRequestBody Body;
        
        public GetListHotelsRequest() {
        }
        
        public GetListHotelsRequest(IHM_Reservation.WebServiceConsultation.GetListHotelsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListHotelsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public GetListHotelsRequestBody() {
        }
        
        public GetListHotelsRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListHotelsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListHotelsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IHM_Reservation.WebServiceConsultation.GetListHotelsResponseBody Body;
        
        public GetListHotelsResponse() {
        }
        
        public GetListHotelsResponse(IHM_Reservation.WebServiceConsultation.GetListHotelsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListHotelsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IHM_Reservation.WebServiceConsultation.Hotel[] GetListHotelsResult;
        
        public GetListHotelsResponseBody() {
        }
        
        public GetListHotelsResponseBody(IHM_Reservation.WebServiceConsultation.Hotel[] GetListHotelsResult) {
            this.GetListHotelsResult = GetListHotelsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListVolsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListVols", Namespace="http://tempuri.org/", Order=0)]
        public IHM_Reservation.WebServiceConsultation.GetListVolsRequestBody Body;
        
        public GetListVolsRequest() {
        }
        
        public GetListVolsRequest(IHM_Reservation.WebServiceConsultation.GetListVolsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListVolsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string to;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime dateStart;
        
        public GetListVolsRequestBody() {
        }
        
        public GetListVolsRequestBody(string from, string to, System.DateTime dateStart) {
            this.from = from;
            this.to = to;
            this.dateStart = dateStart;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetListVolsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetListVolsResponse", Namespace="http://tempuri.org/", Order=0)]
        public IHM_Reservation.WebServiceConsultation.GetListVolsResponseBody Body;
        
        public GetListVolsResponse() {
        }
        
        public GetListVolsResponse(IHM_Reservation.WebServiceConsultation.GetListVolsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetListVolsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public IHM_Reservation.WebServiceConsultation.Vol[] GetListVolsResult;
        
        public GetListVolsResponseBody() {
        }
        
        public GetListVolsResponseBody(IHM_Reservation.WebServiceConsultation.Vol[] GetListVolsResult) {
            this.GetListVolsResult = GetListVolsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : IHM_Reservation.WebServiceConsultation.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<IHM_Reservation.WebServiceConsultation.Service1Soap>, IHM_Reservation.WebServiceConsultation.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IHM_Reservation.WebServiceConsultation.GetListHotelsResponse IHM_Reservation.WebServiceConsultation.Service1Soap.GetListHotels(IHM_Reservation.WebServiceConsultation.GetListHotelsRequest request) {
            return base.Channel.GetListHotels(request);
        }
        
        public IHM_Reservation.WebServiceConsultation.Hotel[] GetListHotels(string city) {
            IHM_Reservation.WebServiceConsultation.GetListHotelsRequest inValue = new IHM_Reservation.WebServiceConsultation.GetListHotelsRequest();
            inValue.Body = new IHM_Reservation.WebServiceConsultation.GetListHotelsRequestBody();
            inValue.Body.city = city;
            IHM_Reservation.WebServiceConsultation.GetListHotelsResponse retVal = ((IHM_Reservation.WebServiceConsultation.Service1Soap)(this)).GetListHotels(inValue);
            return retVal.Body.GetListHotelsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IHM_Reservation.WebServiceConsultation.GetListHotelsResponse> IHM_Reservation.WebServiceConsultation.Service1Soap.GetListHotelsAsync(IHM_Reservation.WebServiceConsultation.GetListHotelsRequest request) {
            return base.Channel.GetListHotelsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IHM_Reservation.WebServiceConsultation.GetListHotelsResponse> GetListHotelsAsync(string city) {
            IHM_Reservation.WebServiceConsultation.GetListHotelsRequest inValue = new IHM_Reservation.WebServiceConsultation.GetListHotelsRequest();
            inValue.Body = new IHM_Reservation.WebServiceConsultation.GetListHotelsRequestBody();
            inValue.Body.city = city;
            return ((IHM_Reservation.WebServiceConsultation.Service1Soap)(this)).GetListHotelsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IHM_Reservation.WebServiceConsultation.GetListVolsResponse IHM_Reservation.WebServiceConsultation.Service1Soap.GetListVols(IHM_Reservation.WebServiceConsultation.GetListVolsRequest request) {
            return base.Channel.GetListVols(request);
        }
        
        public IHM_Reservation.WebServiceConsultation.Vol[] GetListVols(string from, string to, System.DateTime dateStart) {
            IHM_Reservation.WebServiceConsultation.GetListVolsRequest inValue = new IHM_Reservation.WebServiceConsultation.GetListVolsRequest();
            inValue.Body = new IHM_Reservation.WebServiceConsultation.GetListVolsRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.dateStart = dateStart;
            IHM_Reservation.WebServiceConsultation.GetListVolsResponse retVal = ((IHM_Reservation.WebServiceConsultation.Service1Soap)(this)).GetListVols(inValue);
            return retVal.Body.GetListVolsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IHM_Reservation.WebServiceConsultation.GetListVolsResponse> IHM_Reservation.WebServiceConsultation.Service1Soap.GetListVolsAsync(IHM_Reservation.WebServiceConsultation.GetListVolsRequest request) {
            return base.Channel.GetListVolsAsync(request);
        }
        
        public System.Threading.Tasks.Task<IHM_Reservation.WebServiceConsultation.GetListVolsResponse> GetListVolsAsync(string from, string to, System.DateTime dateStart) {
            IHM_Reservation.WebServiceConsultation.GetListVolsRequest inValue = new IHM_Reservation.WebServiceConsultation.GetListVolsRequest();
            inValue.Body = new IHM_Reservation.WebServiceConsultation.GetListVolsRequestBody();
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.dateStart = dateStart;
            return ((IHM_Reservation.WebServiceConsultation.Service1Soap)(this)).GetListVolsAsync(inValue);
        }
    }
}
